from typing import Protocol, Optional
from shared.models import FileMetadata, WriteRequest, WriteResult, Heartbeat, ClockStatus, LogEntry


class MetadataRepo(Protocol):
    def get_file_metadata(self, file_id: str) -> Optional[FileMetadata]: ...
    def upsert_file_metadata(self, meta: FileMetadata) -> FileMetadata: ...
    def choose_replica_nodes(self, file_id: str, replication_factor: int = 3) -> list[str]: ...


class StorageDataGateway(Protocol):
    def store_on_node(self, node_id: str, req: WriteRequest) -> bool: ...
    def read_from_node(self, node_id: str, file_id: str) -> Optional[str]: ...
    def delete_from_node(self, node_id: str, file_id: str) -> bool: ...


class NodeHealthGateway(Protocol):
    def heartbeat(self, node_id: str) -> Heartbeat: ...
    def list_live_nodes(self) -> list[str]: ...


class ConsensusEngine(Protocol):
    def get_current_leader(self) -> Optional[str]: ...
    def replicate_log(self, entry: LogEntry) -> bool: ...
    def start_election(self) -> str: ...


class ClockMonitor(Protocol):
    def collect_offsets(self, node_ids: list[str]) -> dict[str, int]: ...
    def cluster_time_status(self, node_ids: list[str]) -> list[ClockStatus]: ...